server:
  port: 8080

ml:
  service:
    url: http://ml-service:8000/v1

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:portdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false